# Generated by Django 5.2.4 on 2025-07-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='name',
            new_name='item',
        ),
    ]
