# Generated by Django 5.2.4 on 2025-07-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'managed': False},
        ),
    ]
