# Generated by Django 4.2.23 on 2025-08-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transactionitems_transactions_alter_items_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
